// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourApi.Data;

#nullable disable

namespace TourApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710095614_AddTourDescription")]
    partial class AddTourDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBooking")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.Property<int>("TravelAgentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Bookings");

                    b.HasIndex("TourId")
                        .HasDatabaseName("IX_Bookings_TourId");

                    b.HasIndex("TouristId")
                        .HasDatabaseName("IX_Bookings_TouristId");

                    b.HasIndex("TravelAgentId")
                        .HasDatabaseName("IX_Bookings_TravelAgentId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Cities");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_Cities_CountryId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("FlagUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IsoName")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Countries");

                    b.HasIndex("IsoName")
                        .IsUnique()
                        .HasDatabaseName("IX_Countries_IsoName");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Countries_Name");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.EmailConfirmationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_EmailConfirmationTokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailConfirmationTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_EmailConfirmationTokens_UserId");

                    b.ToTable("EmailConfirmationTokens", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Experience")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Employees");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_UserId");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_PersonalInfo_Gender", "[Gender] = 'F' OR [Gender] = 'M'");
                        });

                    b.HasDiscriminator().HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TourApi.Models.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ExternalLogins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ExternalLogins_UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalLogins_Provider_ProviderUserId");

                    b.ToTable("ExternalLogins", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("StarRating")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Hotels");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Hotels_CityId");

                    b.ToTable("Hotels", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.HotelImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_HotelImages");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("IX_HotelImages_HotelId");

                    b.ToTable("HotelImages", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.HotelService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_HotelServices");

                    b.ToTable("HotelServices", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.HotelServiceMapping", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("HotelServiceId")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "HotelServiceId")
                        .HasName("PK_HotelServiceMappings");

                    b.HasIndex("HotelServiceId")
                        .HasDatabaseName("IX_HotelServiceMappings_HotelServiceId");

                    b.ToTable("HotelServiceMappings", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_PasswordResetTokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordResetTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PasswordResetTokens_UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTourGuideId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("money");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Tours");

                    b.HasIndex("AssignedTourGuideId")
                        .HasDatabaseName("IX_Tours_AssignedTourGuideId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Tours_Code");

                    b.HasIndex("CreatedByEmployeeId")
                        .HasDatabaseName("IX_Tours_CreatedByEmployeeId");

                    b.ToTable("Tours", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.TourDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("EstimatedArrivalDate")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EstimatedDepartureDate")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Sequence")
                        .HasColumnType("tinyint");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_TourDetails");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_TourDetails_CityId");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("IX_TourDetails_HotelId");

                    b.HasIndex("TourId")
                        .HasDatabaseName("IX_TourDetails_TourId");

                    b.ToTable("TourDetails", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.TourImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_TourImages");

                    b.HasIndex("TourId")
                        .HasDatabaseName("IX_TourImages_TourId");

                    b.ToTable("TourImages", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.TouringHistory", b =>
                {
                    b.Property<int>("TouristId")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("TouristId", "TourId")
                        .HasName("PK_TouringHistories");

                    b.HasIndex("TourId")
                        .HasDatabaseName("IX_TouringHistories_TourId");

                    b.ToTable("TouringHistories", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.Tourist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Tourists");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Tourists_UserId");

                    b.ToTable("Tourists", null, t =>
                        {
                            t.HasCheckConstraint("CK_PersonalInfo_Gender1", "[Gender] = 'F' OR [Gender] = 'M'");
                        });
                });

            modelBuilder.Entity("TourApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("binary(64)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Username");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TourApi.Models.Admin", b =>
                {
                    b.HasBaseType("TourApi.Models.Employee");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_PersonalInfo_Gender", "[Gender] = 'F' OR [Gender] = 'M'");
                        });

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("TourApi.Models.TourGuide", b =>
                {
                    b.HasBaseType("TourApi.Models.Employee");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_PersonalInfo_Gender", "[Gender] = 'F' OR [Gender] = 'M'");
                        });

                    b.HasDiscriminator().HasValue("TourGuide");
                });

            modelBuilder.Entity("TourApi.Models.TravelAgent", b =>
                {
                    b.HasBaseType("TourApi.Models.Employee");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_PersonalInfo_Gender", "[Gender] = 'F' OR [Gender] = 'M'");
                        });

                    b.HasDiscriminator().HasValue("TravelAgent");
                });

            modelBuilder.Entity("TourApi.Models.Booking", b =>
                {
                    b.HasOne("TourApi.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Tours_TourId");

                    b.HasOne("TourApi.Models.Tourist", "Tourist")
                        .WithMany("Bookings")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Tourists_TouristId");

                    b.HasOne("TourApi.Models.Employee", "TravelAgent")
                        .WithMany("Bookings")
                        .HasForeignKey("TravelAgentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Employees_TravelAgentId");

                    b.Navigation("Tour");

                    b.Navigation("Tourist");

                    b.Navigation("TravelAgent");
                });

            modelBuilder.Entity("TourApi.Models.City", b =>
                {
                    b.HasOne("TourApi.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cities_Countries_CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TourApi.Models.EmailConfirmationToken", b =>
                {
                    b.HasOne("TourApi.Models.User", "User")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmailConfirmationTokens_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourApi.Models.Employee", b =>
                {
                    b.HasOne("TourApi.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("TourApi.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourApi.Models.ExternalLogin", b =>
                {
                    b.HasOne("TourApi.Models.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ExternalLogins_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourApi.Models.Hotel", b =>
                {
                    b.HasOne("TourApi.Models.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Hotels_Cities_CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("TourApi.Models.HotelImage", b =>
                {
                    b.HasOne("TourApi.Models.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HotelImages_Hotels_HotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TourApi.Models.HotelServiceMapping", b =>
                {
                    b.HasOne("TourApi.Models.Hotel", "Hotel")
                        .WithMany("HotelServiceMappings")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HotelServiceMappings_Hotels_HotelId");

                    b.HasOne("TourApi.Models.HotelService", "HotelService")
                        .WithMany("HotelServiceMappings")
                        .HasForeignKey("HotelServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HotelServiceMappings_HotelServices_HotelServiceId");

                    b.Navigation("Hotel");

                    b.Navigation("HotelService");
                });

            modelBuilder.Entity("TourApi.Models.PasswordResetToken", b =>
                {
                    b.HasOne("TourApi.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetTokens_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourApi.Models.RefreshToken", b =>
                {
                    b.HasOne("TourApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourApi.Models.Tour", b =>
                {
                    b.HasOne("TourApi.Models.TourGuide", "AssignedTourGuide")
                        .WithMany()
                        .HasForeignKey("AssignedTourGuideId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tours_Employees_AssignedTourGuideId");

                    b.HasOne("TourApi.Models.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Tours_Employees_CreatedByEmployeeId");

                    b.Navigation("AssignedTourGuide");

                    b.Navigation("CreatedByEmployee");
                });

            modelBuilder.Entity("TourApi.Models.TourDetail", b =>
                {
                    b.HasOne("TourApi.Models.City", "City")
                        .WithMany("TourDetails")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourDetails_Cities_CityId");

                    b.HasOne("TourApi.Models.Hotel", "Hotel")
                        .WithMany("TourDetails")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TourDetails_Hotels_HotelId");

                    b.HasOne("TourApi.Models.Tour", "Tour")
                        .WithMany("TourDetails")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourDetails_Tours_TourId");

                    b.Navigation("City");

                    b.Navigation("Hotel");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourApi.Models.TourImage", b =>
                {
                    b.HasOne("TourApi.Models.Tour", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TourImages_Tours_TourId");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourApi.Models.TouringHistory", b =>
                {
                    b.HasOne("TourApi.Models.Tour", "Tour")
                        .WithMany("TouringHistories")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_TouringHistories_Tours_TourId");

                    b.HasOne("TourApi.Models.Tourist", "Tourist")
                        .WithMany("TouringHistories")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TouringHistories_Tourists_TouristId");

                    b.Navigation("Tour");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TourApi.Models.Tourist", b =>
                {
                    b.HasOne("TourApi.Models.User", "User")
                        .WithOne("Tourist")
                        .HasForeignKey("TourApi.Models.Tourist", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Tourists_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourApi.Models.City", b =>
                {
                    b.Navigation("Hotels");

                    b.Navigation("TourDetails");
                });

            modelBuilder.Entity("TourApi.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("TourApi.Models.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TourApi.Models.Hotel", b =>
                {
                    b.Navigation("HotelServiceMappings");

                    b.Navigation("Images");

                    b.Navigation("TourDetails");
                });

            modelBuilder.Entity("TourApi.Models.HotelService", b =>
                {
                    b.Navigation("HotelServiceMappings");
                });

            modelBuilder.Entity("TourApi.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");

                    b.Navigation("TourDetails");

                    b.Navigation("TouringHistories");
                });

            modelBuilder.Entity("TourApi.Models.Tourist", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TouringHistories");
                });

            modelBuilder.Entity("TourApi.Models.User", b =>
                {
                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("Employee");

                    b.Navigation("ExternalLogins");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tourist");
                });
#pragma warning restore 612, 618
        }
    }
}
